### ISSUE TITLE
Contact (from legacy project)

### ISSUE THREAD

**Issue by micst** [micst/CTestAdapter#11]
Find the original issue [here](https://github.com/micst/CTestTestAdapter/issues/7)

@toeb wrote:

Hi - sorry there is no PM in github so I had to create an issue here ;)

I saw that you created CTestAdapter. (also ctesttestadapter was a mouthful - even though more consistent - I thought about CTestAdapter as well but found it too ambiguous - mistake ) It looks very good :) and thanks for the credits.

I see the project uses CMake to add dotnet projects and I have a couple of questions because I might want to add some stuff to [cmakepp](https://github.com/toeb/cmakepp) to make dotnet/CMake easier

 - Did you think of the CMake code to create these projects yourself and/or do you have resources for dotnet/CMake.
 - Does using CMake and dotnet work well? (in comparison to normal visual studio csproj) or are major features missing normally available in VS?
 - Why did you do it? (cross platfrom dotnet build / multitarget version (VS10-15) or just because you like cmake?

If you could elabarate it would be greatly appreciated

**Comment by micst** [comment]
#### Did you think of the CMake code to create these projects yourself and/or do you have resources for dotnet/CMake?

In short: yes, but only if my boss says OK.

A bit more detailed:

We are working on a mixed C++/C# software with the requirement that the C++ part of the code must be portable to some other special system. After evaluating and discussing a set of different possible build configurators or even relying completely on the native Microsoft way, we decided to choose the power of CMake and add the features that where missing to us: C# support. [Here](https://gitlab.kitware.com/cmake/cmake/merge_requests?scope=all&utf8=%E2%9C%93&state=merged&author_username=stuermic)'s a rough overview of the C# support changes in CMake.

Our focus is **not** to enhance CMake and Visual Studio extensions because we can. We just want the best tools possible to make developing and testing our software as easy and flexible as possible. On the other hand we get great feedback from the CMake community to make C# support even better step by step.

#### Does using CMake and dotnet work well? (in comparison to normal visual studio csproj) or are major features missing normally available in VS?

CMake and .NET work perfectly well for all our current purposes. For some overview about issues just check the [C# issues at kitware](https://gitlab.kitware.com/cmake/cmake/issues?scope=all&utf8=%E2%9C%93&state=all&label_name[]=lang%3Acsharp). Some are still open or awaiting answers but most of them are solved. There is also at least [one project](https://github.com/bemehiser/cmake_csharp_wpf_example) on github which shows how to configure C# projects.

With target and source files properties that can be set individually we achieved to migrate very large projects from a standard build to CMake build. There is some learning curve how the targets must be configured and some things have to be taken into account of course:

 - as with any cmake project: if you re-generate, any changes made with the IDE will go away. So you really need to configure everything within the ``CMakeLists.txt`` and included ``*.cmake`` files.
 - currently only ``Visual Studio*`` generators are supported, no nmake, or any other generators which may even use msvc compilers
 - all things like referencing standard assemblies and setting special properties like connections between designer and code behind files may not feel intuitive at the begin. It's propably best to start with some example and, of course, read the CMake documentation.
   - especially any target- and source files-property starting with ``VS_`` may be of interest!

#### Why did you do it? (cross platfrom dotnet build / multitarget version (VS10-15) or just because you like cmake?

First I have quite some CMake/.NET background from adding C# support to CMake. While I'm not very experienced in .NET itself I appreciate the power and flexibility of CMake.

For the CTestAdapter, I chose CMake as configuration tool because it makes supporting the different Visual Studio versions easy and it allows smart configuration of versioning and generation of things like the vsix manifest and assembly info.

I don't like editing version numbers etc. in several places and files like the manifests should not be duplicated if they are almost the same for all Visual Studio versions.

Finally it is nice to have some mechanism that verifies during configuration if I am building a valid git tag without changes which is based on the release branch to avoid releases may be not well defined.

----

I hope this helped you a bit.

**Comment by toeb** [comment]
That helped a lot - Thank you👍
